def instructions():
    print("How To Play")
    print("Blackjack is played with one deck of 52-cards.")
    print("Aces may be counted as 1 or 11 points, 2 to 9 according to pip value, and tens and face cards count as ten points.")
    print("The value of a hand is the sum of the point values of the individual cards. Except, a blackjack is the highest hand, consisting of an ace and any 10-point card, and it outranks all other 21-point hands.")
    print("The player is prompted to place a bet within the amount of 2 and 500 dollars.")
    print("After the players have bet, the dealer will give two cards to each player and two cards to himself.")
    print("Once the player has been dealt two cards, they will be asked to stand or hit.")
    print("Stand implies that you want to keep the cards you have and Hit implies you want the dealer to deal you one more card from the deck.")
    print("If the dealer goes over 21 points, then any player who didn't already bust will win.")
    print("If the dealer does not bust, then the higher point total between the player and dealer will win.")
    print("The Winner wins the cash that has been betted upon in the beginning of the game.")
    print()
